---
- name: Configure Docker and Swarm
  hosts: all
  become: yes
  roles:
    - common

- name: Initialize Swarm Manager
  hosts: managers
  become: yes
  vars_files:
    - ../deployment/db_secrets.yml
  roles:
    - swarm-manager

- name: Join Swarm Workers
  hosts: workers
  become: yes
  roles:
    - swarm-worker

- name: Setup Database Storage
  hosts: db_nodes
  become: yes
  roles:
    - ebs-mount

- name: Deploy Application Stack
  hosts: managers
  become: yes
  vars:
    app_version: "v1.0.0"
  vars_files:
    - ../deployment/db_secrets.yml
  roles:
    - swarm-deploy
